### ISSUE TITLE
Moving to Go modules for dependency management

### ISSUE THREAD

**Issue by surajnarwade** [uswitch/vault-creds#27]
we have `vendor` directory for dependency, but I think it will be good if we have dependency management file (`dep` maybe)

**Comment by Joseph-Irving** [comment]
we have https://github.com/uswitch/vault-creds/blob/master/vendor/vendor.json

But we should probably just switch to Go modules anyway and scrap the whole vendor dir

**Comment by surajnarwade** [comment]
@Joseph-Irving :+1: 

I will rename this issue then
